### ISSUE TITLE
Sign up - Dog is not saving

### ISSUE THREAD

**Issue by mewing0328** [VenBak/PlayDate#71]
When signing up, new dog to new owner is not saving

**Comment by smithm4949** [comment]
We discussed this issue, pretty sure this is because we didn't update how we are sending data to the backend.

Since you have to have a dog at signup, we only need one POST to create owner. There is no need to call to dog to post.

req.body should look like {username, first_name, ... , dogs: [{ name, breed, ... , age}]

**Comment by smithm4949** [comment]
Fixed in most recent PR from Myles
